// <auto-generated />
using System;
using Datos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Datos.Migrations
{
    [DbContext(typeof(PandoraContext))]
    [Migration("20230717014734_TableImg")]
    partial class TableImg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Datos.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contra")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Clientes__3214EC076DCCDC14");

                    b.HasIndex("RolId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Datos.Models.ItemCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clase")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Material")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Serie")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ItemClie__3214EC0703581D96");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ItemCliente", (string)null);
                });

            modelBuilder.Entity("Datos.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC0776790576");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Datos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contra")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC07ED49F880");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Datos.Models.Cliente", b =>
                {
                    b.HasOne("Datos.Models.Role", "Rol")
                        .WithMany("Clientes")
                        .HasForeignKey("RolId")
                        .HasConstraintName("FK__Clientes__RolId__398D8EEE");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Datos.Models.ItemCliente", b =>
                {
                    b.HasOne("Datos.Models.Cliente", "Usuario")
                        .WithMany("ItemClientes")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__ItemClien__Image__3C69FB99");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Datos.Models.Usuario", b =>
                {
                    b.HasOne("Datos.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .HasConstraintName("FK__Usuarios__RolId__3F466844");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Datos.Models.Cliente", b =>
                {
                    b.Navigation("ItemClientes");
                });

            modelBuilder.Entity("Datos.Models.Role", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
